*
* file generated by qgraf-3.1.4
* output= 'amp.h' ;
* style= 'form.sty' ;
* model= 'qcd.mod';
* in= a[q] ;
* out= q[k1], Q[k2], g[k3] ;
* loops= 0;
* loop_momentum= ;
* options= ;
*
*--#[ d1:
   1
  *VQQA(1,-q+k1, -2,-k1, -1,q)
  *VQQG(-4,-k2, 2,q-k1, -6,-k3)
*--#] d1:
*--#[ d2:
   1
  *VQQA(-4,-k2, 2,-q+k2, -1,q)
  *VQQG(1,q-k2, -2,-k1, -6,-k3)
*--#] d2:
*--#[ Declarations:
#$n = 2;
*--#] Declarations:
*
* end
*
