*
* file generated by qgraf-3.1.4
* output= 'amp/a2qqgg0.h' ;
* style= 'amp/form.sty' ;
* model= 'amp/qcd.mod' ;
* in= a[q] ;
* out= q[k1], Q[k2], g[k3], g[k4] ;
* loops= 0 ;
* loop_momentum= l ;
* options= ;
*
*--#[ d1:
   -1
  *VQQA(1,-q+k1, -2,-k1, -1,q)
  *VQQG(-4,-k2, 4,k2+k3, -6,-k3)
  *VQQG(3,-k2-k3, 2,q-k1, -8,-k4)
*--#] d1:
*--#[ d2:
   -1
  *VQQA(1,-q+k1, -2,-k1, -1,q)
  *VQQG(-4,-k2, 4,k2+k4, -8,-k4)
  *VQQG(3,-k2-k4, 2,q-k1, -6,-k3)
*--#] d2:
*--#[ d3:
   1
  *VQQA(1,-q+k1, -2,-k1, -1,q)
  *VGGG(-6,-k3, -8,-k4, 3,k3+k4)
  *VQQG(-4,-k2, 2,q-k1, 4,-k3-k4)
*--#] d3:
*--#[ d4:
   -1
  *VQQA(-4,-k2, 2,-q+k2, -1,q)
  *VQQG(3,k1+k3, -2,-k1, -6,-k3)
  *VQQG(1,q-k2, 4,-k1-k3, -8,-k4)
*--#] d4:
*--#[ d5:
   -1
  *VQQA(-4,-k2, 2,-q+k2, -1,q)
  *VQQG(3,k1+k4, -2,-k1, -8,-k4)
  *VQQG(1,q-k2, 4,-k1-k4, -6,-k3)
*--#] d5:
*--#[ d6:
   1
  *VQQA(-4,-k2, 2,-q+k2, -1,q)
  *VGGG(-6,-k3, -8,-k4, 3,k3+k4)
  *VQQG(1,q-k2, -2,-k1, 4,-k3-k4)
*--#] d6:
*--#[ d7:
   -1
  *VQQG(1,k1+k3, -2,-k1, -6,-k3)
  *VQQG(-4,-k2, 4,k2+k4, -8,-k4)
  *VQQA(3,-k2-k4, 2,-k1-k3, -1,q)
*--#] d7:
*--#[ d8:
   -1
  *VQQG(1,k1+k4, -2,-k1, -8,-k4)
  *VQQG(-4,-k2, 4,k2+k3, -6,-k3)
  *VQQA(3,-k2-k3, 2,-k1-k4, -1,q)
*--#] d8:
*--#[ Declarations:
#$n = 8;
*--#] Declarations:
*
* end
*
