*
* file generated by qgraf-3.1.4
* output= 'amp/a2uUuU0.h' ;
* style= 'amp/form.sty' ;
* model= 'amp/qcd.mod' ;
* in= a[q] ;
* out= u[k1], U[k2], u[k3], U[k4] ;
* loops= 0 ;
* loop_momentum= l ;
* options= ;
*
*--#[ d1:
   1
  *VQQA(1,-q+k1, -2,-k1, -1,q)
  *VQQG(-4,-k2, -6,-k3, 3,k2+k3)
  *VQQG(-8,-k4, 2,q-k1, 4,-k2-k3)
*--#] d1:
*--#[ d2:
   -1
  *VQQA(1,-q+k1, -2,-k1, -1,q)
  *VQQG(-8,-k4, -6,-k3, 3,k3+k4)
  *VQQG(-4,-k2, 2,q-k1, 4,-k3-k4)
*--#] d2:
*--#[ d3:
   1
  *VQQA(-4,-k2, 2,-q+k2, -1,q)
  *VQQG(-8,-k4, -2,-k1, 3,k1+k4)
  *VQQG(1,q-k2, -6,-k3, 4,-k1-k4)
*--#] d3:
*--#[ d4:
   -1
  *VQQA(-4,-k2, 2,-q+k2, -1,q)
  *VQQG(-8,-k4, -6,-k3, 3,k3+k4)
  *VQQG(1,q-k2, -2,-k1, 4,-k3-k4)
*--#] d4:
*--#[ d5:
   -1
  *VQQA(1,-q+k3, -6,-k3, -1,q)
  *VQQG(-4,-k2, -2,-k1, 3,k1+k2)
  *VQQG(-8,-k4, 2,q-k3, 4,-k1-k2)
*--#] d5:
*--#[ d6:
   1
  *VQQA(1,-q+k3, -6,-k3, -1,q)
  *VQQG(-8,-k4, -2,-k1, 3,k1+k4)
  *VQQG(-4,-k2, 2,q-k3, 4,-k1-k4)
*--#] d6:
*--#[ d7:
   -1
  *VQQA(-8,-k4, 2,-q+k4, -1,q)
  *VQQG(-4,-k2, -2,-k1, 3,k1+k2)
  *VQQG(1,q-k4, -6,-k3, 4,-k1-k2)
*--#] d7:
*--#[ d8:
   1
  *VQQA(-8,-k4, 2,-q+k4, -1,q)
  *VQQG(-4,-k2, -6,-k3, 3,k2+k3)
  *VQQG(1,q-k4, -2,-k1, 4,-k2-k3)
*--#] d8:
*--#[ Declarations:
#$n = 8;
*--#] Declarations:
*
* end
*
